### ISSUE TITLE
Wrong Libsodium function in Signature.ed25519PkToCurve25519

### ISSUE THREAD

**Issue by shiundu** [ionspin/kotlin-multiplatform-libsodium#20]
First, thanks for the great work on the library.
 
We had issues with derived public keys that did match what we got from other `Libsodium` libraries. 

Digging deeper (thanks to @andreapizzato) we found that the `crypto_sign_ed25519_sk_to_curve25519 ` has been used to convert public keys instead of `crypto_sign_ed25519_sk_to_curve25519 `

So in the `Signature` object the `ed25519PkToCurve25519` is using the wrong Libsodium function. 

```
actual object Signature {
...
    /**
         * The sodiumJna.crypto_sign_ed25519_pk_to_curve25519() function converts an Ed25519 public key ed25519_pk to an X25519 public key and stores it into x25519_pk.
         */
        actual fun ed25519PkToCurve25519(ed25519PublicKey: UByteArray) : UByteArray {
            val x25519PublicKey = UByteArray(crypto_scalarmult_curve25519_BYTES)
            sodiumJna.crypto_sign_ed25519_sk_to_curve25519(
                x25519PublicKey.asByteArray(),
                ed25519PublicKey.asByteArray()
            )
            return x25519PublicKey
        }
    
        actual fun ed25519SkToCurve25519(ed25519SecretKey: UByteArray) : UByteArray {
            val x25519SecretKey = UByteArray(crypto_scalarmult_curve25519_BYTES)
            sodiumJna.crypto_sign_ed25519_sk_to_curve25519(
                x25519SecretKey.asByteArray(),
                ed25519SecretKey.asByteArray()
            )
            return x25519SecretKey
        }
    ...
}
```

**Comment by ionspin** [comment]
Hi @shiundu, thanks for reporting! I'll look into it over the weekend!

**Comment by ionspin** [comment]
Once again, @shiundu and @andreapizzato thanks for reprting the issue and also providing the cause, it really helps. The fix will be available in 0.8.5-SNAPSHOT in a hour if the build completes successfully on CI.

**Comment by shiundu** [comment]
@ionspin Thanks for quick response and for resolving the issue promptly.

**Comment by shiundu** [comment]
Hey @ionspin,
Thanks for the fix,

I don't mean to bother you, I would just like to know why you needed to upgrade the android minimum sdk from 23 to 24?

**Comment by ionspin** [comment]
Hey @shiundu, no worries, I don't remember having a strong reason for picking 24 I think it was mostly updating to a version that hopefully still receives security updates at that point.
