### ISSUE TITLE
is this compatible with updating GitHub org secrets?

### ISSUE THREAD

**Issue by JonGilmore** [ionspin/kotlin-multiplatform-libsodium#34]
Is it possible to use this wrapper for updating GitHub org secrets ([reference](https://docs.github.com/en/enterprise-server@3.5/rest/actions/secrets#create-or-update-an-organization-secret))? Thanks!

**Comment by ionspin** [comment]
Hi Jon, sure, this is a quick sketch from the reference you provided, you need to re-check it before using it though:
```
    suspend fun githubSecret() : String {
        LibsodiumInitializer.initialize()
        val secret = "Secret".encodeToUByteArray()
        val publicKey = LibsodiumUtil.fromBase64("base64 public key")
        val encrypted = Box.seal(secret, publicKey)
        val encoded = LibsodiumUtil.toBase64(encrypted)
        return encoded
    }
```

Hope this helps!

**Comment by JonGilmore** [comment]
thanks! exactly what I needed
