### ISSUE TITLE
Libsodium return values aren't checked in some (many) places

### ISSUE THREAD

**Issue by HeroBrine1st** [ionspin/kotlin-multiplatform-libsodium#42]
Hi

Looks like this wrapper does not check what libsodium returns on JVM. For example:

https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/bd988cc493799cef82dbf6c2defb4e58e5b8301e/multiplatform-crypto-libsodium-bindings/src/jvmMain/kotlin/com/ionspin/kotlin/crypto/LibsodiumInitializer.kt#L50-L54

https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/bd988cc493799cef82dbf6c2defb4e58e5b8301e/multiplatform-crypto-libsodium-bindings/src/jvmMain/kotlin/com/ionspin/kotlin/crypto/pwhash/PasswordHash.kt#L14-L36

Also on Native, although I'm not sure because I didn't ever use Kotlin/Native FFI:
https://github.com/ionspin/kotlin-multiplatform-libsodium/blob/bd988cc493799cef82dbf6c2defb4e58e5b8301e/multiplatform-crypto-libsodium-bindings/src/nativeMain/kotlin/com/ionspin/kotlin/crypto/generichash/GenericHash.kt#L36-L43

It's not everywhere though, e.g. `crypto_pwhash_str_verify` has a check, although it is used to get the result of verification so check suggests itself.

As said in [FAQ](https://doc.libsodium.org/quickstart#how-do-i-check-if-a-function-call-succeeded), `-1` means call is failed. I think ignored failures can introduce a serious vulnerability, especially under memory pressure (e.g. as a result of a DoS).

I understand that it is pretty rare case, but protection from targeted attacks is worth something like that:

```kotlin

class LibsodiumException: Exception("Libsodium call failed")

fun Int.ensureSuccessful() {
  if(it != 0) throw LibsodiumException()
}
```

For usage in every applicable place:

```kotlin
 actual suspend fun initialize() { 
     sodiumJna = loadLibrary() 
     sodiumJna.sodium_init().ensureSuccessful()
     isPlatformInitialized = true 
 } 
```

(offtopic) Also, do you accept pull requests?

**Comment by ionspin** [comment]
Fix should be available in latest snapshot. Once again, thanks for reporting!
